### PR TITLE
Add import from FranceData

### PR DESCRIPTION
**Pull request by njoyard**
Todo:
* [x] Check group consistency
* [x] ~~Add previous mandates ?~~
* [x] Add addresses and link them to phones

(and sorry for the PR noise, I prefer redoing PRs because codecov doesn't trigger again when adding commits)

### CODE REVIEW

**Comment by jpic** [comment]
> Add previous mandates ?

This can wait until we have a use case ;)

However, is it possible for you to add a model for the "Chamber" ?

Say, we want all data imported from this linked with a foreign key to Chamber(name=Assemblé nationale), and all data from the senate in Chamber(name=Sénat). We should also add Chamber=European Parliament.

What do you think ?

**Comment by njoyard** [comment]
> However, is it possible for you to add a model for the "Chamber" ?

Sure, but how should that link to the rest of the model?  We would need a rep->chamber link for sure, but how about groups and constituencies? And maybe even dossiers?

**Comment by njoyard** [comment]
> However, is it possible for you to add a model for the "Chamber" ?

Sure, but how should that link to the rest of the model?  We would need a rep->chamber link for sure, but how about groups and constituencies? And maybe even dossiers?

**Comment by jpic** [comment]
Well only meps have a group, but maybe we could upgrade the standard to enable an m2m relation between Dossiers and groups too, they are after all, related, even though at this point we'd only be able to link to the group representing chamber.

@bram and @luxcem might have an opinion on this

**Comment by njoyard** [comment]
What I was thinking was that some groups/constituencies/dossiers may be related only to a specific Chamber.

For example, a kind='party' group has a meaning outside of a chamber, but a kind='comittee' group is related to a chamber.

Additionally, dossiers may be related to one or more chambers. If you have a memopol instance with FR senate, FR assembly and EP, you will have EP-specific dossiers, and dossiers that are related to both senate and assembly...

I think there's more thought to put in this before adding a new model so that we don't restrict its usage too much.

**Comment by njoyard** [comment]
Added Chamber model. Group now has a (nullable) FK to Chamber.
I also updated HashableModel.calculate_hash to enable using nullable FK fields in the fingerprint calculation (it just hashes 'None' when the field is null, and works as the existing code when it has something).

**Comment by njoyard** [comment]
Added senate support as a follow-up to https://github.com/SocieteCitoyenne/FranceData/commit/852531cf4de8529480442ef7bfc40cedce88a367

**Comment by njoyard** [comment]
Bumped version number so that users can depend on a version with the Chamber model

**Comment by njoyard** [comment]
Ready to merge

**Pull request merged**
